# Generated by Django 5.0.1 on 2024-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
