# Generated by Django 5.0.1 on 2024-09-16 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_cartitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wishlist',
        ),
    ]
