# Generated by Django 5.0.1 on 2024-09-16 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_rename_cartitem_cart_rename_wishlistitem_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishlistItem',
        ),
    ]
