# Generated by Django 5.0.1 on 2024-09-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_book_google_books_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='google_books_id',
        ),
    ]
