# Generated by Django 5.0.1 on 2024-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_remove_book_google_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='google_books_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
