# Generated by Django 5.0.1 on 2024-09-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_cartitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='google_books_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
