# Generated by Django 5.0.1 on 2024-09-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_wishlistitem_google_books_id_alter_wishlistitem_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='google_books_id',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='google_books_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
