# Generated by Django 5.0.1 on 2024-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_remove_cartitem_book_id_cartitem_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='google_books_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
