# Generated by Django 5.0.1 on 2024-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_wishlist_delete_wishlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
