# Generated by Django 5.0.1 on 2024-09-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_alter_wishlist_unique_together_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
